// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220201022733_NewCreate")]
    partial class NewCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Domain.achizitii", b =>
                {
                    b.Property<Guid>("Iduser")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Idgames")
                        .HasColumnType("TEXT");

                    b.HasKey("Iduser", "Idgames");

                    b.HasIndex("Idgames");

                    b.ToTable("Achizitii");
                });

            modelBuilder.Entity("Domain.games", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Cost")
                        .HasColumnType("REAL");

                    b.Property<int>("Idprod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Domain.login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parola")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Login");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Parola = "mare"
                        },
                        new
                        {
                            Id = 2,
                            Parola = "schema"
                        },
                        new
                        {
                            Id = 3,
                            Parola = "aicea"
                        });
                });

            modelBuilder.Entity("Domain.producator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Daniel Mullins"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mihoyo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Edmund McMillen"
                        });
                });

            modelBuilder.Entity("Domain.user", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("Idlogin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.achizitii", b =>
                {
                    b.HasOne("Domain.games", "games")
                        .WithMany("achizitie")
                        .HasForeignKey("Idgames")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.user", "user")
                        .WithMany("achizitie")
                        .HasForeignKey("Iduser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("games");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.games", b =>
                {
                    b.Navigation("achizitie");
                });

            modelBuilder.Entity("Domain.user", b =>
                {
                    b.Navigation("achizitie");
                });
#pragma warning restore 612, 618
        }
    }
}
